name: humanize_numbers 
description: Convert numbers into their word representation 
version: 1.0.0
documentation: https://github.com/CatHood0/dart-humanize-numbers
homepage: https://github.com/CatHood0/dart-humanize-numbers
repository: https://github.com/CatHood0/dart-humanize-numbers
issue_tracker: https://github.com/CatHood0/dart-humanize-numbers/issues
topics: [text, numbers, number, natural-numbers]

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  meta: ^1.16.0

dev_dependencies:
  test: ^1.25.15
  lints: ^5.0.0
